### ISSUE TITLE
Like structural logging? Coders and testers needed!

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#28]
We could use your help to introduce this feature soon!

Like to help with coding or testing? Please let us know!

See also https://github.com/NLog/NLog/issues/1376

**Comment by ShaneCourtrille** [comment]
I don't have time to help with coding currently but we are looking at moving to Serilog to support our usage of [Seq](http://getseq.net) so I'd love to help with testing of this.

**Comment by 304NotModified** [comment]
Testing would be great! I expect a test package within a few days!

**Comment by 304NotModified** [comment]
almost there with a first alpha!
