### ISSUE TITLE
(JSON) serializer in this library?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#30]
@jods4: (at https://github.com/NLog/yamtp/pull/29)

>  I strongly believe that you shouldn't do the JSON serialization yourself. This is too large to implement inside a logging lib and will surely lead to tons of feature requests by users.

> Yeah, I think it would be much better to use an existing JSON serializer:
> - You have to write _tons_ of test cases to be sure you have a full, correct JSON implementation.
>- Making it _fast_ is difficult and a lot of work.
>- Then there's a ton of things you might want to support (e.g. look at Newtonsoft Json.NET): support for dictionaries, datatables, ignoring non-serializable members, etc. etc.
>- And making it customizable is even worse. People invariably want lots of tweaks to naming, mappings, special types, omitting default values, etc. etc. Again just have a look at Json.NET, it's crazy.

> Bottom line: I think logger and serializer should be two separated libs.
Even if you have ultra-basic internal JSON usage and don't need any fuss at all I would suggest taking a dependency on something like SimpleJSON.NET (probably not the case here).

agree, but then we need to have:

a) a dependency to NLog (back), so we need to merge it with NLog
b)  or a we have to always to inject the ISerializer, which makes this library as less working out of the box. 
c)  or we need to extract the serializer to a new package

What do you think is the best?

**Comment by 304NotModified** [comment]
I'm doubting to release this part as a separate library / package. Maybe integrating into NLog is much easier.  (so option a)

**Comment by 304NotModified** [comment]
@adamchester, @nblumhardt

Your opinion is appreciated :)

**Comment by adamchester** [comment]
Regarding specifically JSON, no I don't think you need or want that here.

Regarding some kind of serialisation/deserialisation, in message templates libraries (like [MessageTemplates](https://github.com/messagetemplates/messagetemplates-csharp) and YAMTP), it makes sense to have them because it's a core feature and strongly tied to how the template is used (capturing and rendering).

From [messagetemplates.org](https://messagetemplates.org/):

> Rendering semantics

> Given a set of property values, and a message template, implementations should render the template by substituting property values into the locations of the corresponding named holes.

> Message template rendering **should optimize for legibility and the conventions, culture, and context into which the message is being rendered**:

> Named holes without corresponding property values may be rendered as the original {...} token, or a blank/empty/sentinel value may be substituted
Numeric values, dates, times and similar data may be rendered in culture-specific format
Complex data may be presented in a format most familiar to the user

Should you move this into NLOG? I'm not sure I have an opinion on that question yet. However I note that both Serilog and [Logary](https://logary.github.io) have opted to put the message template implementations internal and a core part of the library itself.

Hope I understood the issue correctly.

**Comment by nblumhardt** [comment]
Just on the effort of implementing a JSON Serializer; I think it turns out to be a lot less than a _de_serializer would require. Serilog's is only a couple of hundred lines: https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Json/JsonValueFormatter.cs

This is, of course, made simpler by the way Serilog captures data for serialization separately from the step of writing it out. Few bugs and good perf so far, but YMMV.

I might also be off-track here, only time to skim the earlier thread so apologies if this makes no sense at all ;-)

**Comment by 304NotModified** [comment]
> Regarding some kind of serialisation/deserialisation, in message templates libraries (like MessageTemplates  and YAMTP), it makes sense to have them because it's a core feature and strongly tied to how the template is used (capturing and rendering).

It's the serialisation in the message template almost like JSON serialization? 

> Should you move this into NLOG? I'm not sure I have an opinion on that question yet.

If I move it into NLog, I won't create a new separate package, and hence the license to BSD-3. But maybe creating a separate package is another issue

> both Serilog and Logary have opted to put the message template implementations internal and a core part of the library itself.

Thanks ! :)

> This is, of course, made simpler by the way Serilog captures data for serialization separately from the step of writing it out. Few bugs and good perf so far, but YMMV.

But also writing out is done in Serilog itself? 

What's YMMV? ;)

**Comment by jods4** [comment]
@304NotModified 
YMMV = Your Mileage May Vary.

Can you remind me what do we need the JSON serialization for exactly?

I assume that handling the _structured_ logging will be done by some NLog target, i.e. an external package, which may require some JSON dependency (or not).

Unless I'm missing something, we're left with (a) serializing messages for "old-school", non-structured targets and (b) filling `{@bar}` holes. 

For (a) I suggest a plain `.ToString()`. Structured logging code can try to capture rather large objects, it would not be very useful to log large serialized objects into a plain text file, would it?

For (b), as pointed out by @adamchester, this doesn't have to be JSON and in fact the example from Message Templates site is explicitely _not_ JSON. We probably should do something much simpler and more readable, like space-separated `Property: value` and be done with this. What do you think?

RE serilog's JSON implementation:
It's short and not too complex, but it's not trivial either. I see that this file accepts special, already processed value "objects" and this is where a lot of complexity can be. Depending on the intended usage some options are missing (such as neatly formatting the text output) and one has to add test cases for everything. So I still think that's a non-trivial amount of work for a lib like NLog.

**Comment by 304NotModified** [comment]
> Can you remind me what do we need the JSON serialization for exactly?

Destructing, To do something like this (first Serilog example ;))

```c#
var position = new { Latitude = 25, Longitude = 134 };
var elapsedMs = 34;

log.Information("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);
//results: 09:14:22 [Information] Processed { Latitude: 25, Longitude: 134 } in 034 ms.
```

`{ Latitude: 25, Longitude: 134 } ` is JSON (the default?)

But also quote strings and not numbers, is JSON compliant. 

> Like space-separated Property: value and be done with this.

How would ` new { Latitude = 25, Longitude = 134 };` looks then? `{ Latitude = 25 Longitude = 134 }` ? Is that really easier to implement?

> For (b), as pointed out by @adamchester, this doesn't have to be JSON

Indeed, therefor it should be injectable. But there should be a (simple and usable) default?

**Comment by jods4** [comment]
This is my (b) point and it doesn't have to be JSON. In fact the first image on https://messagetemplates.org
renders your example in a text file as 
```
[2016-...] Processed Lat: 25 Long: 134 in 32 ms.
```

That said, the output format is not the most complex aspect of this, processing the parameter is: 
- do you want to support `dynamic` / expandos?
- support `IEnumerable`
- support `IDictionary`
- limit depth
- avoid cycles?
- customization? like custom properties names or ignored properties?
- special interfaces like `IConvertible` to string?

**Comment by nblumhardt** [comment]
> { Latitude: 25, Longitude: 134 } is JSON (the default?)
> But also quote strings and not numbers, is JSON compliant.

It's not actually JSON, instead a simplified representation like @jods4 is suggesting 👍

**Comment by 304NotModified** [comment]
> This is my (b) point and it doesn't have to be JSON.

True. Took here JSON, but could be also JSON-alike. 



> That said, the output format is not the most complex aspect of this, processing the parameter is:
> 
> do you want to support dynamic / expandos? 

yes (expando is a IDictionary)
> support IEnumerable 

yes
> support IDictionary 

yes
> limit depth 

yes
> avoid cycles?

 yes (by limiting depth)
> customization? like custom properties names or ignored properties? 

yes, but not with attributes. It's already in the PR: `  serializationManager.SaveSerializerFunc<Uri>(u => u.Host);`
> special interfaces like IConvertible to string?

not sure, need an example at this hour ;)

**Comment by nblumhardt** [comment]
(Looking back, using JSON would have saved some confusion - we have had a few issues raised about the "missing quotes" etc :-))

**Comment by 304NotModified** [comment]
> It's not actually JSON, instead a simplified representation like @jods4 is suggesting

What's the difference? The missing quotes around the property name?

> using JSON would have saved some confusion

Was thinking that also, as it looks alike, well why isn't then the same? Saves at least some documentation ;) and easier replacement with a full-fledged library (json.net) - although the latter is always possible.

**Comment by nblumhardt** [comment]
A few small differences. The format also supports dictionaries with non-string keys and prints them nicely, since the internal model allows them, even though JSON doesn't.

**Comment by 304NotModified** [comment]
> The format also supports dictionaries with non-string keys and prints them nicely, since the internal model allows them, even though JSON doesn't.

This isn't valid JSON? 

```
{3: "a", 4: "b"}

```

It's at least [JSON5 compatible](https://github.com/json5/json5) ;)

**Comment by nblumhardt** [comment]
Hehe :-) no, not valid in JSON.

**Comment by 304NotModified** [comment]
not sure if there a lot of implementations who don't deserialize that ;)

But that's another discussion ;)

**Comment by adamchester** [comment]
Just in case it helps the discussion, here is the _data model_ of FsMessageTemplates (and Serilog):

```fsharp
/// A key and value pair, used as part of <see cref="TemplatePropertyValue.DictionaryValue" />.
type ScalarKeyValuePair = TemplatePropertyValue * TemplatePropertyValue
/// Describes the kinds of destructured property values that can be
/// captured from a message template.
and TemplatePropertyValue =
| ScalarValue of obj
| SequenceValue of TemplatePropertyValue list
| StructureValue of typeTag:string * values:PropertyNameAndValue list
| DictionaryValue of data: ScalarKeyValuePair list
/// A property and it's associated destructured value.
and PropertyNameAndValue = { Name:string; Value:TemplatePropertyValue }
```

This model is immutable (important because it can get tricky if you try to log mutable values), and log statements (via message templates) are captured into this structure, then rendered into the format suitable for the target/sink (e.g. a console sink could render as text filling in the {holes} with JSON syntax if necessary).

**Comment by jods4** [comment]
If you choose JSON, what are the drawbacks of simply taking a dependency on Json.NET? It's pretty much standard in the .NET world nowadays, especially in ASP.NET Core.
Using Json.NET would provide all the customizations you may ever want and a hardened implementation with good perf.

Relevant? https://twitter.com/Nick_Craver/status/807584122470330369

**Comment by adamchester** [comment]
In Logary, the _data model_ looks like this:

```fsharp
type Value =
  | String of string
  | Bool of bool
  | Float of float
  | Int64 of int64
  | BigInt of bigint
  | Binary of byte [] * ContentType
  | Fraction of int64 * int64
  | Object of Map<string, Value>
  | Array of Value list
```

Logary has a particular focus on metrics too, which is why it has very specific types like `Fraction` and `BigInt`.

**Comment by 304NotModified** [comment]
> If you choose JSON, what are the drawbacks of simply taking a dependency on Json.NET? It's pretty much standard in the .NET world nowadays, especially in ASP.NET Core.

strong naming issues. See also [RestSharp Version 103 removed JSON.NET as a dependency.](https://groups.google.com/forum/#!msg/restsharp/yjGCtOnEYHk/XbKZi0yjN8cJ) : 

> John Sheehan 	
> 
> 4/19/12
> 
> 
> ...
> 
> JSON.NET strong names assemblies and NuGet does not handle this well.
> At. All. When JSON.NET updates their assembly version and people
> update it via NuGet, it breaks RestSharp. There are workarounds and
> hacks, but none are fool proof and most just trade one set of problems
> for another. And the result when things go wrong is I get tons of
> support email I can't answer. Any update to JSON.NET could break
> RestSharp and any lib that depends on RestSharp at an indeterminate
> time. This costs companies real money and it costs me real time that I
> don't have. I don't think that's acceptable.
> 
> ...
> 
>  For the first time in
> months I wrote code for RestSharp because I had time that was no
> longer being spent on ridiculous dependency issues. JSON.NET had to go
> or RestSharp had to.
> 
> I hope this is the last time I ever have to talk about this. Let's all
> move forward.

We had also enough strong naming issues in NLog in the past. JSON.NET is great, strong naming not.

**Comment by nblumhardt** [comment]
Because Serilog's used in projects with varying versions of JSON.NET we've tried to avoid a dependency on it when possible. Too many version compatibility headaches lurking there :-)

**Comment by 304NotModified** [comment]
> Because Serilog's used in projects with varying versions of JSON.NET we've tried to avoid a dependency on it when possible. Too many version compatibility headaches lurking there :-)

Good choice. I see also your doing the strong name "semver compliant". More libraries should do that. 
![image](https://cloud.githubusercontent.com/assets/5808377/21627765/604e244e-d21a-11e6-8115-fef604374fa0.png)

**Comment by 304NotModified** [comment]
FYI,

Will remove the serializer in this library and replace it in the tests with JSON.NET

In NLog it will use the (JSON) serializer implementation there.

Default will be JSON, as it's a standard. Maybe not the best one, but it's better then no-standard

**Comment by 304NotModified** [comment]
done
