### ISSUE TITLE
Fully backwards-compatible with String.Format

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#4]
As NLog uses string.format (and probably other users before), we should be fully backwards-compatible with `String.Format`
# Specs (Composite Formatting)

> Each format item takes the following form and consists of the following components:

```
 {index[,alignment][:formatString]}
```

> The matching braces ("{" and "}") are required.

https://msdn.microsoft.com/en-us/library/txafckwd(v=vs.110).aspx

> Alignment Component
> The optional alignment component is a signed integer indicating the preferred formatted field width. If the value of alignment is less than the length of the formatted string, alignment is ignored and the length of the formatted string is used as the field width. The formatted data in the field is right-aligned if alignment is positive and left-aligned if alignment is negative. If padding is necessary, white space is used. The comma is required if alignment is specified.
# To Do Parse
- [x] index (partly, only 0-9 now)
- [x]  alignment (e.g. `,10`, `-10`
- [x] formatstring
- [x] escaping
- [x] duplicate indexes (e.g. two times `{0}`)
- [x] error on negative index?
# To Do Render
- [x] index
- [ ]  alignment
- [x] formatstring
- [x] escaping
- [x] duplicate indexes (e.g. two times `{0}`)

**Comment by jods4** [comment]
About escaping: I don't think escaping the format string is currently handled. Try `{0:x}}y}` & co. 
BTW: I guess the property name can't contain braces, can it? Do we need to check and error on `{a{bc}`?

Is alignment really supported by message templates? According to https://messagetemplates.org/ I don't think so.

**Comment by 304NotModified** [comment]
> About escaping: I don't think escaping the format string is currently handled. Try {0:x}}y} & co. 
> BTW: I guess the property name can't contain braces, can it? Do we need to check and error on {a{bc}?

I don't think this is needed, but we have to double check t.

> Is alignment really supported by message templates? According to https://messagetemplates.org/ I don't think so.

Nope, but to use it in NLog, it's should be backwards-compatible with `string.format` (the current "template parser")

**Comment by jods4** [comment]
> I don't think this is needed, but we have to double check it.

Speaking of the error in property name?
Because the formatting escape is very required, if only for compatibility with `string.Format` (but also for custom text in format).

> Nope, but to use it in NLog, it's should be backwards-compatible with string.format (the current "template parser")

Ok... is it enough to parse it (and ignore it) or do you want full-fidelity?

**Comment by 304NotModified** [comment]
> I don't think this is needed, but we have to double check it.
> Speaking of the error in property name?

We should double check if `}` and `{` are disallowed in hole names.

> Ok... is it enough to parse it (and ignore it) or do you want full-fidelity?

Full, but it's easy. We need comparability in API **and** behavior . Anyway, I added it to the parser, see #7

**Comment by 304NotModified** [comment]
Some tests of `String.Format`

### Supported (and working)

```
{01} //  = index 1
{00}
{00000}
{0 } //space after (but before gives an error...
{{{0}
{10} //+9
{000000000000000000000000000000000000000000000000000000000001     } 
{0,-10}
{0,10}
{0,10:idontcare}
{0,10:} //empty culture
{0,    -4  :   nl } // spaces around alignment, spaces around format
```

### Not working (Exception)

```
{ 0} //space before
{-1} //negative index
{0 0} //space between
{} //empty hole
{2} //if two args
{0,--10} //min min is not plus
{0,+10} //+ 
{0,:nl} //empty alignment
```

**Comment by jods4** [comment]
Would it hurt to accept `{ 0}`? That's compatible with `string.Format` and may be easier (because consistency).

**Comment by 304NotModified** [comment]
> Would it hurt to accept { 0}? That's compatible with string.Format and may be easier (because consistency).

I think it's more efficient to not support it? After the first char we know what the kind is (number or text). 

(well it depends if we support "{0a}")

**Comment by jods4** [comment]
Indeed... but do we need to support `{0a}` or not? what's the message template spec here?

**Comment by 304NotModified** [comment]
that's being discussed right now! :)

https://gitter.im/messagetemplates/messagetemplates.org

**Comment by jods4** [comment]
Ticking:
- "error on neg. index". There is no error, it's a named hole.
- "index". In #11 we have `HoleIndex` properly set for positional and set to -1 for named.
  We don't need a proper index if the whole list is not positional, as holes are filled in a first-come-first-served basis.

Also unticking escaping, because it's not OK for format string.

**Comment by 304NotModified** [comment]
Important, the string.format won't quote strings, serilog does. This has been tackled with the legacy mode in #17. Maybe make it configurable in NLog.
