### ISSUE TITLE
Should we capture all parameters?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.StructuredEvents#45]
Discussion: should we capture all parameters? Even when not used in the template string?

e.g.

```c#
logger.Info("Send order", 123); 
```

Questions:

1. Should we capture all parameters
2. What will be the name of '123'
3.  How do we keep thinks backwardscompatible? 
    1. e.g. `logger.Info("hello {0}, "a", "b");` - we don't capture "b" currently
    1. We could make a new collection public, message parameters - but all the stuff is already written on  event properties - `${event-properties}`, ` ${all-event-properties}`
    1. We could make it optional (config) and enable it by default in NLog 5
4.  or do we allow only full objects in this case? e.g.
     ```c#
     logger.Info("Send order", new {OrderId = 123}); 
    ```
    1. but then we need to list all properties as arguments?  (OrderId = one property)

**Comment by AnthonySteele** [comment]
IMHO the template string is trying to do two things - produce a compound string containing all the parameters, and also have  a constant string.  This backwards compatible compromise has the side effects that the constant string is less readable, it would be e.g. `Sent order {OrderId} to customer {CustomerId}`; and that when you add more context it is restrictive, you also have to think of a way to talk about the new parameter in the format string. 

I am a fan of this style instead: `logger.Info("Send order to customer", new { OrderId = 123 });` I know that it's not as backwards compatible, but adding another named Id to the log message should be simple. 
e.g. changing it to `logger.Info("Send order to customer", new { OrderId = 123, CustomerId = 456});` is very simple. When you need `CustomerId` for searching or filtering in Kibana it will be there, but until then it won't get in your way. You haven't even changed the message string that you use! 

I prefer a constant string to a template.

**Comment by 304NotModified** [comment]
@nblumhardt @adamchester @AnthonySteele @ianbattersby your input is highly appreciated!

**Comment by 304NotModified** [comment]
@AnthonySteele ow you found it already ;)

It then `logger.Info("Send order", 123); ` not allowed? And what about:

- `logger.Info("Send order", new { OrderId = 123}, new {  CustomerId = 456});` ?
- and  `logger.Info("Send order", new { Order = new { OrderId = 123, CustomerId = 456}});` ?


> I am a fan of this style instead: logger.Info("Send order to customer", new { OrderId = 123, CustomerId = 456});

I have to agree it looks charming, but I'm curious how this looks if you logging to a file.  Like this?

```
Send order to customer
Send order to customer
Send order to customer
Send order to customer
```

**Comment by AnthonySteele** [comment]
The second one with `new { OrderId = 123}, new { CustomerId = 456});` doesn't seem useful to me. You would just concatenate all the values. Is there an advantage to having multiple objects over just one with multiple props?

The third is basically the question of is it a flat list of key-value pairs or a fully recursive structure.

**Comment by AnthonySteele** [comment]
In addition, some people have found value in passing in a mutable `IDictionary<string, object>` because then they can use one as an object that accumulates state cross multiple logging calls inside a method. 
I mean like this:

```csharp
private Order GetOrder(int orderId)
{
   var  logContext = new Dictionary<string, object>();
   logContext.Add("OrderId", orderId)
   logger.Info("Getting order", logContext);

   var order = _repo.ReadOrder(orderId);

   if (order != null)
   {
     logContext.Add("CustomerId", order.CustomerId);
     logger.Info("Got order", logContext);
   }
  else
   {
      logger.Warn("No such order", logContext);
   }

  return order;
}
```

It's not a great example, but I've seen cases where the pattern is useful.

**Comment by adamchester** [comment]
We  (partially) dealt with this difficult question in Serilog
https://github.com/serilog/serilog/issues/737
https://github.com/serilog/serilog/pull/779

**Comment by nblumhardt** [comment]
Just to point to a couple of prior solutions to this, in Serilog you'd use:

```csharp
private Order GetOrder(int orderId)
{
   var  logContext = logger.ForContext("OrderId", orderId);
   logContext.Information("Getting order", logContext);

   var order = _repo.ReadOrder(orderId);

   if (order != null)
   {
     logContext = logContext.ForContext("CustomerId", order.CustomerId);
     logContext.Information("Got order");
   }
   else
   {
      logContext.Warning("No such order");
   }

  return order;
}
```

(There are more idiomatic ways to write it, but the above is structurally the closest.)

And in Microsoft.Extensions.Logging you'd use much more similar code, but push the dictionary on as a scope:

```csharp
     logContext.Add("CustomerId", order.CustomerId);
     using (logger.BeginScope(logContext))
     {
         logger.Info("Got order");
     }
```

**Comment by AnthonySteele** [comment]
What I like about a custom class like the ` logger.ForContext("OrderId", orderId);` example is that it captures that a fully mutable `Dictionary` is perhaps overkill - there is a limited set of operations that you need. i.e. The code that is doing the logging will need to add to and perhaps update the collection, but that's all. The  logger will need to read the values out, but that's all.

**Comment by 304NotModified** [comment]
- I was thinking to capture all parameters, but the unnamed ones will be called "unnamed 1", "unnamed 2". What do you think about this?
- I like the log style of @AnthonySteele , but we won't support it as we will take the direction of Serilog's style. Also from a performance point of view, I have my doubts if this will work well enough for our highly demanding users ;) Thanks for the idea!

**Comment by AnthonySteele** [comment]
#### Regarding absolute performance in `StructuredLogging.Json`:

In this library, when we do `logger.ExtendedInfo("Send order to customer", new { OrderId = 123, CustomerId = 456 });`
[We do reflection](https://github.com/justeat/NLog.StructuredLogging.Json/blob/master/src/NLog.StructuredLogging.Json/LoggerExtensions.cs#L107) in the form of `logProperties.GetType().GetProperties()`  to list the names and then call `PropertyInfo.GetValue` for the value of each property.

I have done a few [BenchmarkDotNet](http://benchmarkdotnet.org/) tests, and the entire `logger.ExtendedInfo` call takes about 1.2ms. 
So far, changes to those lines of reflection code makes no difference at all to the overall time. I would of course accept PRs that change that time for the better and aren't completely unreadable. But for now it's an acceptable latency for our uses.

####  Regarding relative performance:

When compared to template strings, you have different but probably quite parallel performance concerns. `String.Format` is known to be the most flexible but far from the fastest way of working with strings. Extracting embedded names from the string is a bit like object reflection, so it don't see that it would have compelling performance advantage in theory. Metadata for particular call site could likely be cached in both cases.

**Comment by 304NotModified** [comment]
Thanks for the info @AnthonySteele 

Currently we have in the best case a performance of 2 million/sec for the file target (with even on thread), so then 1.2ms is quite a bit ;)



> When compared to template strings, you have different but probably quite parallel performance concerns. String.Format is known to be the most flexible but far from the fastest way of working with strings.

Agree, but I think we have wrote a fast parser and the benefit is that we could case the parse result. Pretty sure we get almost the same performance, of course depending of the object send.

**Comment by AnthonySteele** [comment]
I'm sure that `StructuredLogging.Json` has performance bottlenecks. The only thing that I can say about them now is that they don't seem to be in reflecting over the log properties object.

**Comment by slang25** [comment]
If there was a bottleneck on reflecting over the properties then it's a common pattern to cache the properties and their emitted getters.

**Comment by miyu** [comment]
At the risk of bloating API surface:

Perhaps `logger.info("recv", x)` writes a tuple of two entries and displays format("recv") + format(x) while `logger.infof("recv {X}", x)` does string formatting before printing the first item. In either case, all inputs are stored to e.g. database.

**Comment by miyu** [comment]
Also worthwhile to note JS console.log behavior, namely:

```
console.log(obj1 [, obj2, ..., objN]);
console.log(msg [, subst1, ..., substN]);
```
e.g.
```
var car = "Dodge Charger";
var someObject = {str:"Some text", id:5}; 
console.info("My first car was a", car, ". The object is: ", someObject);
```
vs
```
for (var i=0; i<5; i++) {
  console.log("Hello, %s. You've called me %d times.", "Bob", i+1);
}
```
https://developer.mozilla.org/en-US/docs/Web/API/Console/log  
https://developer.mozilla.org/en-US/docs/Web/API/console#Outputting_text_to_the_console

**Comment by biiiipy** [comment]
Yes, we should definitely capture all parameters. A lot of times, we want to output a simple message and then dump a few properties with it for context.
Instead of ``"unnamed 1"`` for keys we could use something short and simple as ``"prop1"`` or maybe even index as a string ``"0"``

**Comment by ericanastas** [comment]
Personally I don't like the idea of having unnamed parameters. Giving a default name like "unnamed 1" isn't a whole lot better. For any of these options the identifier is really only useful in the context of a single message template. 

However, I also don't think parameters should be dropped. I like the idea above by @biiiipy of just using the index name for parameters.

**Comment by 304NotModified** [comment]
Thanks for the feedback! I think the index name is indeed the best solution
