### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ShaneCourtrille** [NLog/NLog.StructuredEvents#49]
Hate to be asking this since I don't have time to help out but is there any forward movement on this expected or should we be moving over to Serilog?

**Comment by 304NotModified** [comment]
We are working on it, but it had been moved to the main repo. This repo will probably deleted in the future

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/pull/2208

**Comment by 304NotModified** [comment]
anyway, structured logging has been merged in to NLog 4.5 beta
